const products = [{
        id: 0,
        name: "Spier Merlot",
        price: 79.99,
        description: "Rich cherry and red berry scents mingle with mouth-watering caramel and a trace of smoky tobacco in this wine. Aromas of juicy red and black berries, plums, with a eucalyptus and mint undercurrent.This Spier Merlot has gentle tannins and luscious fruit.",
        imgSrc: "http://cdn.shopify.com/s/files/1/0259/0670/8570/products/Spier-Signature-Merlot-Wine_5f277ea1-da9e-41ea-9924-4e95e1f28bf4.jpg?v=1612612752",
        instock: 10,
    },
    {
        id: 1,
        name: "Sweet Red Wine",
        price: 59.99,
        description: "Apart from being higher in residual sugar content, sweet red wines usually have lower alcohol content. These bottles are flavourful and complex. Also, sweet red wines unlike their dry counterparts don't have the full tannic flavors of traditional red wines like Cabernet Franc or Merlot.",
        imgSrc: "./images/sweetred.jpg",
        instock: 8,
    },
    {
        id: 2,
        name: "Sauvignon Blanc",
        price: 79.99,
        description: "Sauvignon Blanc is a white wine grape variety that is most often used to produce dry white wines. Light and refreshing, its unique in that its flavor sets it apart from most other white wine grape varieties.",
        imgSrc: "./images/bellevue-sauvignon-blanc-2019.jpg",
        instock: 3,
    },
    {
        id: 3,
        name: "Brut Champagne",
        price: 129.99,
        description: 'Brut, which means "dry, raw, or unrefined," in French, is the driest (meaning the least sweet) classification of Champagne. To be considered Brut, the Champagne must be made with less than 12 grams of added sugar per liter. Brut Champagne is the most common style of sparkling wine',
        imgSrc: "https://shop.prestonsliquors.co.za/wp-content/uploads/packshots/750928.png",
        instock: 20,
    },
    {
        id: 4,
        name: "Chardonnay",
        price: 89.99,
        description: 'In general, Chardonnay is known to be a relatively dry, medium-bodied white wine emanating fresh, crisp notes of pear, guava, lemon-peel, and apple. Now, if you were to add some oak to the aging process, the above flavors shift dramatically – giving off strong hints of butter, vanilla, English pudding and pineapple.',
        imgSrc: "https://www.excelsior.co.za/wp-content/uploads/2017/10/Chardonnay-2.png",
        instock: 30,
    },
    {
        id: 5,
        name: "Dry white",
        price: 69.99,
        description: 'A dry white is any white wine that is not sweet. Some typical dry white wines include Sauvignon Blanc, Albarino, Pinot Grigio, and Gruner Veltliners. A wine with less than 10 grams of residual sugar is considered dry, and above 30 grams is regarded as sweet wine or a dessert wine.',
        imgSrc: "https://produits.bienmanger.com/23911-0w470h470_Tariquet_Classic_Domaine_Tariquet.jpg",
        instock: 35,
    }

]